### ISSUE TITLE
code is not nic

### ISSUE THREAD

**Issue by RushilKoul** [mellobacon/GameEngine#2]
I no like dis code

**Comment by mellobacon** [comment]
smh you go make your *own* game engine then xd

**Comment by RushilKoul** [comment]
I'm only good at bullying but not coding ;-;

**Comment by RushilKoul** [comment]
to be fair I'm shit at bullying too

**Comment by RushilKoul** [comment]
y'º'u'r''r'e code is good

**Comment by mellobacon** [comment]
yay!

**Comment by mellobacon** [comment]
closing because this isnt a issue
